// Utility Functions
class Utils {
    static getStableUserId() {
            let userId = localStorage.getItem('userId');
                    if (userId) return userId;
                            
                                    userId = this.generateStableUserId();
                                            localStorage.setItem('userId', userId);
                                                    
                                                            if (!localStorage.getItem('joinDate')) {
                                                                        localStorage.setItem('joinDate', new Date().toISOString());
                                                                                }
                                                                                        
                                                                                                return userId;
                                                                                                    }

                                                                                                        static generateStableUserId() {
                                                                                                                const components = [
                                                                                                                            navigator.userAgent, navigator.language,
                                                                                                                                        navigator.hardwareConcurrency || 'unknown',
                                                                                                                                                    screen.width + 'x' + screen.height,
                                                                                                                                                                new Date().getTimezoneOffset()
                                                                                                                                                                        ];
                                                                                                                                                                                
                                                                                                                                                                                        let hash = 0;
                                                                                                                                                                                                const str = components.join('|');
                                                                                                                                                                                                        for (let i = 0; i < str.length; i++) {
                                                                                                                                                                                                                    const char = str.charCodeAt(i);
                                                                                                                                                                                                                                hash = ((hash << 5) - hash) + char;
                                                                                                                                                                                                                                            hash = hash & hash;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    return 'user_' + Math.abs(hash).toString(36) + '_' + Date.now();
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                            static formatTime(seconds) {
                                                                                                                                                                                                                                                                                    const hours = Math.floor(seconds / 3600);
                                                                                                                                                                                                                                                                                            const minutes = Math.floor((seconds % 3600) / 60);
                                                                                                                                                                                                                                                                                                    const secs = seconds % 60;
                                                                                                                                                                                                                                                                                                            return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    static showLoading(message = 'Loading...') {
                                                                                                                                                                                                                                                                                                                            const loading = document.getElementById('loading');
                                                                                                                                                                                                                                                                                                                                    const status = loading.querySelector('.loading-status');
                                                                                                                                                                                                                                                                                                                                            status.textContent = message;
                                                                                                                                                                                                                                                                                                                                                    loading.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                            static hideLoading() {
                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('loading').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                        }, 500);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }