const express = require('express');
const router = express.Router();
const { createClient } = require('@supabase/supabase-js');
const bcrypt = require('bcrypt');

// Debug: Check environment variables
console.log('SUPABASE_URL:', process.env.SUPABASE_URL);
console.log('SUPABASE_ANON_KEY:', process.env.SUPABASE_ANON_KEY ? '***SET***' : 'MISSING');

// Initialize Supabase client
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase environment variables!');
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // --- TEST ROUTE ---
    router.get('/', (req, res) => {
        res.json({ message: 'User Routes Working with Supabase. Ready to implement Register/Login.' });
        });

        // --- USER REGISTRATION ROUTE ---
        router.post('/register', async (req, res) => {
            try {
                    const { walletId, password } = req.body;

                            // 1. Check if user already exists in Supabase
                                    const { data: existingUser, error: checkError } = await supabase
                                                .from('users')
                                                            .select('*')
                                                                        .eq('walletId', walletId)
                                                                                    .single();

                                                                                            if (existingUser) {
                                                                                                        return res.status(400).json({ message: 'Wallet ID already registered.' });
                                                                                                                }

                                                                                                                        // 2. Hash the password
                                                                                                                                const salt = await bcrypt.genSalt(10);
                                                                                                                                        const hashedPassword = await bcrypt.hash(password, salt);

                                                                                                                                                // 3. Insert new user into Supabase
                                                                                                                                                        const { data: newUser, error: insertError } = await supabase
                                                                                                                                                                    .from('users')
                                                                                                                                                                                .insert([
                                                                                                                                                                                                {
                                                                                                                                                                                                                    walletId: walletId,
                                                                                                                                                                                                                                        password: hashedPassword,
                                                                                                                                                                                                                                                            balance: 0
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        ])
                                                                                                                                                                                                                                                                                                    .select();

                                                                                                                                                                                                                                                                                                            if (insertError) {
                                                                                                                                                                                                                                                                                                                        throw insertError;
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                        // 4. Success response
                                                                                                                                                                                                                                                                                                                                                res.status(201).json({ message: 'User registered successfully!', user: newUser });

                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                            console.error('Registration error:', error);
                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ message: 'Server error during registration.', error: error.message });
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                        // --- USER LOGIN ROUTE ---
                                                                                                                                                                                                                                                                                                                                                                        router.post('/login', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                    const { walletId, password } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                            // 1. Find user in Supabase
                                                                                                                                                                                                                                                                                                                                                                                                    const { data: user, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                            .select('*')
                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq('walletId', walletId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (error || !user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(400).json({ message: 'Invalid wallet ID or password.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 2. Check password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const isPasswordValid = await bcrypt.compare(password, user.password);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!isPasswordValid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(400).json({ message: 'Invalid wallet ID or password.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 3. Success response (without password)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { password: _, ...userWithoutPassword } = user;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ message: 'Login successful!', user: userWithoutPassword });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Login error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ message: 'Server error during login.', error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = router;