const express = require('express');
const router = express.Router();
const { createClient } = require('@supabase/supabase-js');
const bcrypt = require('bcrypt');

// Supabase client
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

// Test route
router.get('/', (req, res) => {
    res.json({ message: 'User API Working' });
    });

    // Register user
    router.post('/register', async (req, res) => {
        try {
                const { walletId, password, referredBy, telegramId, telegramUsername } = req.body;

                        // Check if user exists
                                const { data: existingUser } = await supabase
                                            .from('users')
                                                        .select('*')
                                                                    .eq('walletId', walletId)
                                                                                .single();

                                                                                        if (existingUser) {
                                                                                                    return res.status(400).json({ message: 'Wallet ID already registered' });
                                                                                                            }

                                                                                                                    // Hash password
                                                                                                                            const hashedPassword = await bcrypt.hash(password, 10);

                                                                                                                                    // Create user
                                                                                                                                            const { data: newUser, error } = await supabase
                                                                                                                                                        .from('users')
                                                                                                                                                                    .insert([{
                                                                                                                                                                                    walletId,
                                                                                                                                                                                                    password: hashedPassword,
                                                                                                                                                                                                                    balance: 0,
                                                                                                                                                                                                                                    referredBy: referredBy || null,
                                                                                                                                                                                                                                                    telegramId: telegramId || null,
                                                                                                                                                                                                                                                                    telegramUsername: telegramUsername || null
                                                                                                                                                                                                                                                                                }])
                                                                                                                                                                                                                                                                                            .select();

                                                                                                                                                                                                                                                                                                    if (error) throw error;

                                                                                                                                                                                                                                                                                                            res.json({ 
                                                                                                                                                                                                                                                                                                                        message: 'User registered successfully',
                                                                                                                                                                                                                                                                                                                                    user: { walletId, balance: 0 }
                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ message: 'Server error', error: error.message });
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                            // Login user
                                                                                                                                                                                                                                                                                                                                                            router.post('/login', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                        const { walletId, password } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                // Find user
                                                                                                                                                                                                                                                                                                                                                                                        const { data: user, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                    .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                .select('*')
                                                                                                                                                                                                                                                                                                                                                                                                                            .eq('walletId', walletId)
                                                                                                                                                                                                                                                                                                                                                                                                                                        .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                if (error || !user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(400).json({ message: 'Invalid credentials' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Check password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const validPassword = await bcrypt.compare(password, user.password);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!validPassword) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(400).json({ message: 'Invalid credentials' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Return user without password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { password: _, ...userData } = user;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ message: 'Login successful', user: userData });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ message: 'Server error', error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Generate referral
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        router.post('/generate-referral', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const code = Math.random().toString(36).substring(2, 8).toUpperCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        referralLink: `https://nmx-mining-app.onrender.com?ref=${code}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                referralCode: code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Get user stats
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    router.get('/stats/:walletId', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { walletId } = req.params;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data: user } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select('balance')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq('walletId', walletId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    walletId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                balance: user?.balance || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: 'Stats retrieved'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ message: 'Error getting stats', error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = router;