const express = require('express');
const router = express.Router();
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

// Admin credentials (in production, use proper auth)
const ADMIN_USERNAME = 'admin';
const ADMIN_PASSWORD = 'admin123';

// Admin login
router.post('/login', (req, res) => {
    const { username, password } = req.body;
        
            if (username === ADMIN_USERNAME && password === ADMIN_PASSWORD) {
                    res.json({ success: true, message: 'Admin login successful' });
                        } else {
                                res.status(401).json({ success: false, message: 'Invalid credentials' });
                                    }
                                    });

                                    // Get all users
                                    router.get('/users', async (req, res) => {
                                        try {
                                                const { data: users, error } = await supabase
                                                            .from('users')
                                                                        .select('*')
                                                                                    .order('created_at', { ascending: false });

                                                                                            if (error) throw error;

                                                                                                    // Remove passwords from response
                                                                                                            const usersWithoutPasswords = users.map(user => {
                                                                                                                        const { password, ...userWithoutPassword } = user;
                                                                                                                                    return userWithoutPassword;
                                                                                                                                            });

                                                                                                                                                    res.json({ success: true, users: usersWithoutPasswords });
                                                                                                                                                        } catch (error) {
                                                                                                                                                                res.status(500).json({ success: false, message: error.message });
                                                                                                                                                                    }
                                                                                                                                                                    });

                                                                                                                                                                    // Get platform statistics
                                                                                                                                                                    router.get('/stats', async (req, res) => {
                                                                                                                                                                        try {
                                                                                                                                                                                // Total users
                                                                                                                                                                                        const { data: users, error: usersError } = await supabase
                                                                                                                                                                                                    .from('users')
                                                                                                                                                                                                                .select('*');

                                                                                                                                                                                                                        if (usersError) throw usersError;

                                                                                                                                                                                                                                // Total balance
                                                                                                                                                                                                                                        const totalBalance = users.reduce((sum, user) => sum + (user.balance || 0), 0);

                                                                                                                                                                                                                                                // Telegram users
                                                                                                                                                                                                                                                        const telegramUsers = users.filter(user => user.telegramId).length;

                                                                                                                                                                                                                                                                // Recent users (last 7 days)
                                                                                                                                                                                                                                                                        const weekAgo = new Date();
                                                                                                                                                                                                                                                                                weekAgo.setDate(weekAgo.getDate() - 7);
                                                                                                                                                                                                                                                                                        const recentUsers = users.filter(user => new Date(user.created_at) > weekAgo).length;

                                                                                                                                                                                                                                                                                                res.json({
                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                        stats: {
                                                                                                                                                                                                                                                                                                                                        totalUsers: users.length,
                                                                                                                                                                                                                                                                                                                                                        telegramUsers,
                                                                                                                                                                                                                                                                                                                                                                        recentUsers,
                                                                                                                                                                                                                                                                                                                                                                                        totalBalance: totalBalance.toFixed(2),
                                                                                                                                                                                                                                                                                                                                                                                                        averageBalance: (totalBalance / users.length).toFixed(2) || 0
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ success: false, message: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Delete user
                                                                                                                                                                                                                                                                                                                                                                                                                                            router.delete('/users/:walletId', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { walletId } = req.params;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .delete()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq('walletId', walletId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (error) throw error;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true, message: 'User deleted successfully' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ success: false, message: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = router;